### ISSUE TITLE
SwipeR in Quarto documents & external images

### ISSUE THREAD

**Issue by werkstattcodes** [stla/swipeR#1]
Hello,

Many thanks for this very promising package. I was wondering whether it's actually possible to use swipeR in a quarto document for images which are imported. Unfortunate, it wasn't clear to me from the documentation and my attempts were futile.

I was able to create a carousel in quarto when linking to images hosted on another website, but couldn't get it working for images which are saved in my project's directory.

Grateful for any hint. Many thanks. R

**Comment by stla** [comment]
Hello,

Never tried. I would have said the same way you use for a linked image should work by replacing the link with the path of the image, but you surely tried that. Maybe ask the question on StackOverflow.

**Comment by werkstattcodes** [comment]
> Hello,
> 
> Never tried. I would have said the same way you use for a linked image should work by replacing the link with the path of the image, but you surely tried that. Maybe ask the question on StackOverflow.

Many thanks. Indeed, that's what I tried. Will ask at SO.

**Comment by stla** [comment]
I have an idea. Convert your image in base64 encoding:

```r
library(base64enc)
b64 <- dataURI(file = "yourImage.png", mime = "image/png")
```

Then I'm sure this should work in the Quarto file:

```r
library(swipeR)
library(htmltools)

wrapper <- swipeRwrapper(
  tags$img(src = b64),
)

swipeR(wrapper, height = "100%")
```

**Comment by werkstattcodes** [comment]
Hello,

many thanks for your reply and suggestion. 

Indeed, your approach works. I am able to display images from external files.

A new problem now is how to scale the images so that they are properly displayed in the carousel (not cropped or resized without respecting dimension ratios). 

For reference, below my quarto file demonstrating how to use the external image files and quarto. Many thanks again.

Should i find an efficient solution to the sizing issue, I am happy to post it here.

`---
title: "SwipeR test"
format: html
---


```{r}
#| warning: false
library(tidyverse)
library(swipeR)
library(here)
library(htmltools)
```


# plot with default size
```{r}
mtcars %>%
  ggplot() +
  labs(title = "plot_7_5") +
  geom_point(aes(x = mpg, y = disp))

ggsave(filename = "plot_7_5.png")
```

# plot which is higher than default (10 instead of 7 inch)
```{r}
#| fig-width: 7
#| fig-height: 10

mtcars %>%
  ggplot() +
  labs(title = "plot_7_10") +
  geom_point(aes(x = mpg, y = disp))

ggsave(
  filename = "plot_7_10.png")
```

# plot which is with smaller width than default
```{r}
#| fig-width: 3
#| fig-height: 5

mtcars %>%
  ggplot() +
  labs(title = "plot_3_5") +
  geom_point(aes(x = mpg, y = disp))

ggsave(filename = "plot_3_5.png")
```

# Plot with same height as carousel container and width scaled

5 inch (300 dpi) => 1500px => /5 => 300px => 1 inch

7 inch (300 dpi) => 2100px => /5 => 420px => 1,4 inch

Get's inflated in carousel.
```{r}
#| fig-height: 1
#| fig-width: 1.4

mtcars %>%
  ggplot() +
  labs(title = "plot_420_300") +
  geom_point(aes(x = mpg, y = disp))

ggsave(filename = "plot_420_300.png")

```


```{r}
library(base64enc)
plot_7_5 <- dataURI(file = here::here("plot_7_5.png"), mime = "image/png")

plot_7_10 <- dataURI(file = here::here("plot_7_10.png"), mime = "image/png")

plot_3_5 <- dataURI(file = here::here("plot_3_5.png"), mime = "image/png")

plot_420_300 <- dataURI(file = here::here("plot_420_300.png"), mime = "image/png")
```
 
```{r}
wrapper <- swipeRwrapper(
  tags$img(src = plot_7_5),
  tags$img(src = plot_7_10),
  tags$img(src = plot_3_5),
  tags$img(src = plot_420_300 ),
  tags$img(src = "https://swiperjs.com/demos/images/nature-1.jpg"),
  tags$img(src = "https://swiperjs.com/demos/images/nature-2.jpg")
)
```
 
```{r}
#| echo: true

swipeR(
  wrapper,
  navigationColor = "red",
  height = "300px",
  width = "100%",
  rewind = TRUE,
  zoom = FALSE,
  scrollbar = FALSE,
  thumbsPerView = 4,
  thumbs = FALSE
)
```
`

**Comment by stla** [comment]
Use the `style` attribute in `img`. See the bottom of my `README` file here, there's an example.
