### ISSUE TITLE
Accessibility options

### ISSUE THREAD

**Issue by Tristanjmeyers** [stla/swipeR#2]
Hello - I really like this package, it works very well. However, I wanted to add some accessibility options, in particular, using the keyboard arrow keys to move between images in the carousel. Is this possible to enable, i.e. accessibility = TRUE?

**Comment by stla** [comment]
Hello,

What is an "accessibility option"? 

Take a look a the documentation (google **swiper.js**) and say me if you find such a thing. I'll implement it if it is available.

**Comment by Tristanjmeyers** [comment]
Thanks for that!

Looks like it is supported in swiper.js:

```
const swiper = new Swiper('.swiper', {
  keyboard: {
    enabled: true,
    onlyInViewport: false,
  },
});
```

source:
https://swiperjs.com/swiper-api#keyboard-control

**Comment by stla** [comment]
Ok nice. I'll keep you informed when I'll do the update.

**Comment by stla** [comment]
Done. It works.

```r
remotes:install_github("stla/swipeR")
```

*Example:* 

```r
library(swipeR)
library(htmltools)

wrapper <- swipeRwrapper(
  tags$img(src = "https://swiperjs.com/demos/images/nature-1.jpg"),
  tags$img(src = "https://swiperjs.com/demos/images/nature-2.jpg"),
  tags$img(src = "https://swiperjs.com/demos/images/nature-3.jpg"),
  tags$img(src = "https://swiperjs.com/demos/images/nature-4.jpg"),
  tags$img(src = "https://swiperjs.com/demos/images/nature-5.jpg"),
  tags$img(src = "https://swiperjs.com/demos/images/nature-6.jpg"),
  tags$img(src = "https://swiperjs.com/demos/images/nature-7.jpg"),
  tags$img(src = "https://swiperjs.com/demos/images/nature-8.jpg")
)

swipeR(
  wrapper, height = "500px", width = "70%", thumbs = TRUE, thumbsPerView = 4,
  keyboard = list(enabled = TRUE, onlyInViewport = TRUE, pageUpDown = TRUE),
  on = list(reachEnd = htmlwidgets::JS("function() {alert('the end');}"))
)
```

**Comment by Tristanjmeyers** [comment]
Thanks, works like a charm! Appreciate that.

**Comment by stla** [comment]
Cool. Do not hesitate if you find other options.

**Comment by stla** [comment]
I think I will change the interface. It's annoying to enter this list. `keyboard = TRUE` should be more convenient to enable the keyboard control with the other values as true. The list is for users who want other controls. By the way I didn't see the impact of `onlyInViewPort`, did you?

**Comment by Tristanjmeyers** [comment]
Yea I'm not sure what that did tbh.

`Keyboard = True` would be good, but also leaving in `pageUpDown` option is a nice feature.

**Comment by stla** [comment]
There are three possibilities now:

- `keyboard = TRUE`, which automatically sets `inViewPortOnly` and `pageUpDown` to `TRUE` as well
- `keyboard = FALSE`
- or the list for full control of the options

**Comment by Tristanjmeyers** [comment]
Thanks so much for this!
